const mysql = require('mysql');
const supertest = require('supertest');
const app = require('../index.js');
const request = supertest(app);

// describe('My Test Suite', () => {
//   it('My Test Case', () => {
//     expect(true).toEqual(true);
//   });
// });

describe('Test the data generated by seed function in database', () => {
  const connection = mysql.createConnection({
    host: 'localhost',
    user: 'root',
    password: '',
    database: 'productDetails'
  });

  beforeEach(() => {
    connection.connect();
  });

  afterEach(() => {
    connection.end();
  });

  //test for seed function
  test('Should test if the database is seeded', () => {
    connection.query('SELECT * FROM products', (err, data) => {
      if(err) {
        console.log('test failed- ', err);
      }
      var dbEntries = data.length;
      expect(dbEntries).toBe(100);
    });
  });
});

// test GET request
describe('GET request', () => {
  it("GET request", async done => {
    const res = await request.get('/products/0/');
    expect(res.body).toBeDefined();
    done();
  });
})
